version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.11.1
        environment:
          DATABASE_HOST: 0.0.0.0
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: test_userdb
          DATABASE_SYNCHRONIZE: true
          POKEMON_API_URL: https://pokeapi.co/api/v2/pokemon

      - image: cimg/postgres:15.10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_userdb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:e2e
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: .
workflows:
  build_and_test:
    jobs:
      - build_and_test
